// <auto-generated />
namespace Scrum.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddTablesIssueTypeAndPriority : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTablesIssueTypeAndPriority));
        
        string IMigrationMetadata.Id
        {
            get { return "201608231000462_Add-Tables-IssueType-And-Priority"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
